---
- name: Configure proxy system-wide
  ansible.builtin.blockinfile:
    path: /etc/environment
    marker: "# {mark} ANSIBLE PROXY"
    block: |
      http_proxy=http://{{ proxy_ip }}:{{ proxy_port }}
      https_proxy=http://{{ proxy_ip }}:{{ proxy_port }}
      HTTP_PROXY=http://{{ proxy_ip }}:{{ proxy_port }}
      HTTPS_PROXY=http://{{ proxy_ip }}:{{ proxy_port }}
      all_proxy=socks5://{{ proxy_ip }}:{{ proxy_port }}
      ALL_PROXY=socks5://{{ proxy_ip }}:{{ proxy_port }}
  when: proxy_scope.system_wide

- name: Remove proxy system-wide
  ansible.builtin.blockinfile:
    path: /etc/environment
    marker: "# {mark} ANSIBLE PROXY"
    state: absent
  when: proxy_remove.system_wide

- name: Configure proxy for shell sessions
  ansible.builtin.copy:
    dest: /etc/profile.d/ansible_proxy.sh
    owner: root
    group: root
    mode: '0644'
    content: |
        export http_proxy="http://{{ proxy_ip }}:{{ proxy_port }}"
        export https_proxy="http://{{ proxy_ip }}:{{ proxy_port }}"
        export HTTP_PROXY="http://{{ proxy_ip }}:{{ proxy_port }}"
        export HTTPS_PROXY="http://{{ proxy_ip }}:{{ proxy_port }}"
        export all_proxy="socks5://{{ proxy_ip }}:{{ proxy_port }}"
        export ALL_PROXY="socks5://{{ proxy_ip }}:{{ proxy_port }}"
        export no_proxy="localhost,{{ proxy_ip }}"
        export NO_PROXY="localhost,{{ proxy_ip }}"
  when: proxy_scope.shell_session

- name: Remove proxy of shell sessions
  ansible.builtin.file:
    path: /etc/profile.d/ansible_proxy.sh
    state: absent
  when: proxy_remove.shell_session

- name: Configure proxy for systemd services
  ansible.builtin.include_tasks:
    file: systemd_services_proxy.yml

